[[constraint]]
  name = "github.com/tidepool-org/go-common"
  source = "github.com/mdblp/go-common"
  branch = "master"

[[constraint]]
  name = "github.com/nicksnyder/go-i18n"
  version = "=v2.0.0-beta.6"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.0.0"
  
[prune]
  go-tests = true
  unused-packages = true